### ISSUE TITLE
unable to open spree admin page

### ISSUE THREAD

**Issue by cleverlemming** [jaymendoza/spree-blogging-spree#4]
I installed blogging_spree on the default spree install with sample data and got errors when I tried to access the /admin page. I uninstalled blogging_spree and my admin page is back. I apologize for not copying the stack trace when it happened but will go back and try to replicate as time permits

**Comment by jaymendoza** [comment]
My assumption here is that you are using edge Spree. Up until a few minutes ago, only 0.9.3 was supported. I just merged in a patch that adds compatibility with the latest Spree code.
