### ISSUE TITLE
Archive doesn't show blog entries

### ISSUE THREAD

**Issue by pkordel** [jaymendoza/spree-blogging-spree#9]
Hi, I installed your extension in a clean spree 0.10.2 app and created 2 entries. They don't show up in the archive side menu. I'm on Firefox 3.6.3.
Cool extension, just what I need to go live!
Cheers

**Comment by jaymendoza** [comment]
Were you able to solve this issue? I am currently recovering from tendinitis and so I've been unable to do any coding/testing in the last few months. I can answer any questions you may have, though. Let me know.

**Comment by pkordel** [comment]
I didn't have the time to dig into it yet. Sorry to hear about your tendinitis, I've had similar issues...
